All midfielders Data

In [6]:
import pandas as pd 
sofascore=pd.read_csv('data/atacking_match_data.csv')
fbref_match=pd.read_csv('data/defensive_match_data.csv')

In [9]:
sofascore

,Unnamed: 0,Player,Pos,Min,PrgC,PrgP,xAG,xG,Gls-xG,PPA,Att 3rd
0,0,Dominic Solanke,FW,90,0,2,0.4,0.9,0.1,0,9
1,1,Son Heung-min,LW,90,5,4,1.3,1.0,0.0,1,15
2,2,Brennan Johnson,RW,52,2,1,0.1,0.0,0.0,2,7
3,3,Timo Werner,RW,38,0,2,0.4,0.0,0.0,1,13
4,4,Pape Matar Sarr,"LM,RM",90,0,1,0.0,0.5,-0.5,1,7
5,5,Yves Bissouma,CM,78,0,2,0.0,0.0,0.0,0,1
6,6,Lucas Bergvall,CM,12,1,2,0.0,0.0,0.0,1,4
7,7,Dejan Kulusevski,RM,78,5,2,0.0,0.1,0.9,1,14
8,8,James Maddison,LM,12,2,0,0.5,0.1,-0.1,0,4
9,9,Destiny Udogie,LB,90,1,4,0.0,0.0,0.0,0,9
10,10,Micky van de Ven,CB,78,0,1,0.0,0.1,-0.1,0,1
11,11,Archie Gray,CB,12,0,0,0.0,0.0,0.0,0,0
12,12,Cristian Romero,CB,14,0,0,0.0,0.0,0.0,0,0
13,13,Radu Drăgușin,CB,76,0,2,0.0,0.0,0.0,0,0
14,14,Pedro Porro,RB,90,1,4,0.2,0.1,-0.1,0,17
15,15,Fraser Forster,GK,90,0,0,0.0,0.0,0.0,0,0
16,16,Nicolas Jackson,FW,75,5,0,0.0,0.3,-0.3,0,16
17,17,Christopher Nkunku,FW,15,0,0,0.0,0.0,0.0,0,2
18,18,Jadon Sancho,LW,90,8,6,0.0,0.4,0.6,5,34
19,19,Pedro Neto,RW,85,4,2,0.2,0.1,-0.1,1,27
20,20,Noni Madueke,RW,5,1,0,0.0,0.0,0.0,0,2
21,21,Cole Palmer,AM,89,5,7,0.5,1.7,0.3,2,31
22,22,João Félix,AM,1,0,0,0.0,0.0,0.0,0,0
23,23,Enzo Fernández,DM,90,1,10,0.0,0.1,0.9,4,29
24,24,Roméo Lavia,DM,45,0,2,0.1,0.0,0.0,0,3
25,25,Malo Gusto,RB,45,0,1,0.0,0.0,0.0,0,8
26,26,Marc Cucurella,LB,89,1,5,0.3,0.0,0.0,2,18
27,27,Renato Veiga,LB,1,0,0,0.0,0.0,0.0,0,0
28,28,Levi Colwill,CB,90,0,3,0.0,0.2,-0.2,0,2
29,29,Benoît Badiashile,CB,90,0,4,0.0,0.0,0.0,0,2
30,30,Moisés Caicedo,"DM,RB",90,1,5,0.0,0.0,0.0,0,14
31,31,Robert Sánchez,GK,90,0,0,0.0,0.0,0.0,0,0

In [13]:
match_stats=pd.merge(sofascore,fbref_match,left_on='Player',right_on='Name',how='inner')
match_stats.to_csv('Match_stats.csv',index=False)

All midfielders_join

In [60]:
import pandas as pd 
sofascore_mid=pd.read_csv('data/sofascore_premier_defensive_stats_midfielders.csv')
fbref_mid=pd.read_csv('data/premier_midfielders_atacking_stats.csv')

In [61]:
sofascore_mid

,Name,Minutes played,Appearances,Tackles,Interceptions,Clearances,Ground duels won,Ground duels won %,Total duels won,Aerial duels won %,Aerial duels won,Total duels won %
0,Cole Palmer,1300,15,10,5,5,63,56.25,63,0.00,0,55.26
1,Kevin De Bruyne,561,9,5,3,2,17,33.33,18,16.67,1,31.58
2,James Maddison,965,15,16,8,14,68,54.40,73,50.00,5,54.07
3,Mateo Kovačić,880,11,22,5,6,44,51.16,49,100.00,5,53.85
4,Bruno Fernandes,1253,15,32,11,14,60,50.00,70,41.67,10,48.61
...,...,...,...,...,...,...,...,...,...,...,...,...
183,Ryan Sessegnon,12,1,0,1,1,0,0.00,0,0.00,0,0.00
184,Ryan Fraser,304,7,6,1,8,12,66.67,14,40.00,2,60.87
185,Yunus Konak,26,4,1,0,0,1,12.50,3,50.00,2,25.00
186,James McAtee,2,2,0,0,0,0,0.00,0,0.00,0,0.00
187,Harrison Armstrong,2,2,0,0,0,1,25.00,1,0.00,0,25.00

In [62]:
sofascore_mid = sofascore_mid.drop_duplicates()

In [63]:
sofascore_mid

,Name,Minutes played,Appearances,Tackles,Interceptions,Clearances,Ground duels won,Ground duels won %,Total duels won,Aerial duels won %,Aerial duels won,Total duels won %
0,Cole Palmer,1300,15,10,5,5,63,56.25,63,0.00,0,55.26
1,Kevin De Bruyne,561,9,5,3,2,17,33.33,18,16.67,1,31.58
2,James Maddison,965,15,16,8,14,68,54.40,73,50.00,5,54.07
3,Mateo Kovačić,880,11,22,5,6,44,51.16,49,100.00,5,53.85
4,Bruno Fernandes,1253,15,32,11,14,60,50.00,70,41.67,10,48.61
...,...,...,...,...,...,...,...,...,...,...,...,...
183,Ryan Sessegnon,12,1,0,1,1,0,0.00,0,0.00,0,0.00
184,Ryan Fraser,304,7,6,1,8,12,66.67,14,40.00,2,60.87
185,Yunus Konak,26,4,1,0,0,1,12.50,3,50.00,2,25.00
186,James McAtee,2,2,0,0,0,0,0.00,0,0.00,0,0.00
187,Harrison Armstrong,2,2,0,0,0,1,25.00,1,0.00,0,25.00

In [64]:
fbref_mid
fbref_mid = fbref_mid.drop_duplicates()
fbref_mid

,Player,Pos,MP,Min,PrgC,PrgP,xAG,xG,Gls,Gls-xG,PPA,Att 3rd
0,Tyler Adams,MF,6,345,1,13,0.4,1.0,0,-1.0,1,36
1,Asher Agbinone,MF,2,6,2,0,0.0,0.0,0,0.0,0,6
2,Carlos Alcaraz,MF,1,10,4,6,0.1,0.1,0,-0.1,1,9
3,Edson Álvarez,MF,11,630,7,34,0.4,0.1,0,-0.1,7,77
4,Elliot Anderson,"MF,FW",14,817,20,42,2.0,0.8,0,-0.8,5,206
...,...,...,...,...,...,...,...,...,...,...,...,...
158,Joe Willock,"MF,FW",12,451,16,20,1.1,0.5,0,-0.5,2,109
159,Harry Winks,MF,11,865,12,59,1.0,0.2,0,-0.2,3,98
160,Yehor Yarmoliuk,MF,11,322,3,15,0.1,0.4,0,-0.4,4,74
161,Ryan Yates,MF,15,1124,12,30,0.7,1.6,1,-0.6,3,179
162,Martin Ødegaard,MF,8,665,24,74,1.5,1.8,1,-0.8,25,213

In [65]:
len(sofascore_mid)

188

In [66]:
len(fbref_mid)

163

Cambiamos nombres para que sean iguales

In [67]:
from difflib import get_close_matches

# Obtener los nombres que no coinciden
missing_names = set(sofascore_mid['Name']) - set(fbref_mid['Player'])
missing_names_list = set(fbref_mid['Player']) - set(sofascore_mid['Name'])

# Encontrar los nombres más parecidos
matches = {}
for name in missing_names:
    close_match = get_close_matches(name, missing_names_list, n=1, cutoff=0.8)  # Ajusta 'cutoff' si es necesario
    matches[name] = close_match[0] if close_match else None

# Cambiar los nombres en sofascore_mid
sofascore_mid['Name'] = sofascore_mid['Name'].replace(matches)

# Imprimir los cambios realizados
for original, match in matches.items():
    if match:
        print(f"Cambiado: {original} -> {match}")
    else:
        print(f"{original} -> Sin coincidencia")

Marcus Tavernier -> Sin coincidencia
Wes Burns -> Sin coincidencia
Cambiado: Will Smallbone -> William Smallbone
Nathan Broadhead -> Sin coincidencia
Samuel Amo-Ameyaw -> Sin coincidencia
Noni Madueke -> Sin coincidencia
Savinho -> Sin coincidencia
Cambiado: Yunus Konak -> Yunus Emre Konak
Georginio Rutter -> Sin coincidencia
Amad Diallo -> Sin coincidencia
Dango Ouattara -> Sin coincidencia
Bobby Decordova-Reid -> Sin coincidencia
Jack Grealish -> Sin coincidencia
Rayan Aït Nouri -> Sin coincidencia
Marcus Rashford -> Sin coincidencia
Antoine Semenyo -> Sin coincidencia
Fabio Carvalho -> Sin coincidencia
Samuel Edozie -> Sin coincidencia
James McAtee -> Sin coincidencia
Cambiado: Emiliano Buendía -> Emi Buendía
Mohammed Kudus -> Sin coincidencia
Kasey McAteer -> Sin coincidencia
Callum Hudson-Odoi -> Sin coincidencia
Kaoru Mitoma -> Sin coincidencia
Jack Harrison -> Sin coincidencia
Renato Veiga -> Sin coincidencia
Timo Werner -> Sin coincidencia
Ryan Fraser -> Sin coincidencia
Alejandro Garnacho -> Sin coincidencia
Jack Clarke -> Sin coincidencia
Jaden Philogene-Bidace -> Sin coincidencia
Tyrick Mitchell -> Sin coincidencia
Crysencio Summerville -> Sin coincidencia
Jacob Ramsey -> Sin coincidencia
Harvey Barnes -> Sin coincidencia
Manuel Ugarte -> Sin coincidencia
Lamare Bogarde -> Sin coincidencia
Mads Roerslev -> Sin coincidencia
Leon Bailey -> Sin coincidencia
Luis Sinisterra -> Sin coincidencia
Mykhaylo Mudryk -> Sin coincidencia
Jarrod Bowen -> Sin coincidencia
Ramón Sosa -> Sin coincidencia
Nélson Semedo -> Sin coincidencia
Jesper Lindstrøm -> Sin coincidencia
Myles Lewis-Skelly -> Sin coincidencia
Harvey Elliott -> Sin coincidencia
Cambiado: Idrissa Gueye -> Idrissa Gana Gueye
Jadon Sancho -> Sin coincidencia
Harry Wilson -> Sin coincidencia
Rodrigo Gomes -> Sin coincidencia
Alex Iwobi -> Sin coincidencia
Wilson Odobert -> Sin coincidencia
Sammie Szmodics -> Sin coincidencia
Chiedozie Ogbene -> Sin coincidencia
James Garner -> Sin coincidencia
Matt Doherty -> Sin coincidencia
Antony -> Sin coincidencia
Anthony Elanga -> Sin coincidencia
Simon Adingra -> Sin coincidencia

In [68]:
fbref_mid

,Player,Pos,MP,Min,PrgC,PrgP,xAG,xG,Gls,Gls-xG,PPA,Att 3rd
0,Tyler Adams,MF,6,345,1,13,0.4,1.0,0,-1.0,1,36
1,Asher Agbinone,MF,2,6,2,0,0.0,0.0,0,0.0,0,6
2,Carlos Alcaraz,MF,1,10,4,6,0.1,0.1,0,-0.1,1,9
3,Edson Álvarez,MF,11,630,7,34,0.4,0.1,0,-0.1,7,77
4,Elliot Anderson,"MF,FW",14,817,20,42,2.0,0.8,0,-0.8,5,206
...,...,...,...,...,...,...,...,...,...,...,...,...
158,Joe Willock,"MF,FW",12,451,16,20,1.1,0.5,0,-0.5,2,109
159,Harry Winks,MF,11,865,12,59,1.0,0.2,0,-0.2,3,98
160,Yehor Yarmoliuk,MF,11,322,3,15,0.1,0.4,0,-0.4,4,74
161,Ryan Yates,MF,15,1124,12,30,0.7,1.6,1,-0.6,3,179
162,Martin Ødegaard,MF,8,665,24,74,1.5,1.8,1,-0.8,25,213

In [69]:
midfielders_stats=pd.merge(fbref_mid,sofascore_mid,left_on='Player',right_on='Name',how='inner')
midfielders_stats.to_csv('midfielders_stats.csv',index=False)

In [ ]:
midfielders_stats

,Player,Pos,MP,Min,PrgC,PrgP,xAG,xG,Gls,Gls-xG,...,Appearances,Tackles,Interceptions,Clearances,Ground duels won,Ground duels won %,Total duels won,Aerial duels won %,Aerial duels won,Total duels won %
0,Tyler Adams,MF,6,345,1,13,0.4,1.0,0,-1.0,...,6,20,14,7,22,55.00,29,100.00,7,61.70
1,Carlos Alcaraz,MF,1,10,4,6,0.1,0.1,0,-0.1,...,1,0,1,0,0,0.00,1,100.00,1,25.00
2,Edson Álvarez,MF,11,630,7,34,0.4,0.1,0,-0.1,...,11,18,10,13,31,51.67,44,65.00,13,55.00
3,Elliot Anderson,"MF,FW",14,817,20,42,2.0,0.8,0,-0.8,...,14,29,7,15,70,57.85,82,66.67,12,58.99
4,André,MF,11,685,4,28,0.2,0.1,0,-0.1,...,11,28,6,9,45,65.22,46,25.00,1,63.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,Joe Willock,"MF,FW",12,451,16,20,1.1,0.5,0,-0.5,...,12,12,2,3,24,43.64,25,14.29,1,40.32
135,Harry Winks,MF,11,865,12,59,1.0,0.2,0,-0.2,...,11,12,4,12,20,48.78,24,40.00,4,47.06
136,Yehor Yarmoliuk,MF,11,322,3,15,0.1,0.4,0,-0.4,...,11,11,6,9,17,38.64,20,60.00,3,40.82
137,Ryan Yates,MF,15,1124,12,30,0.7,1.6,1,-0.6,...,15,24,15,32,60,52.17,92,64.00,32,55.76
138,Martin Ødegaard,MF,8,665,24,74,1.5,1.8,1,-0.8,...,8,9,1,1,30,44.12,32,100.00,2,45.71

In [ ]:
import plotly.express as px
import pandas as pd

# Crear un DataFrame de ejemplo
data = {'Metric': ['Passing', 'Dribbling', 'Shooting', 'Defending', 'Physicality'],
        'Enzo Fernandez': [85, 70, 80, 65, 90],
        'Martin Odegard ': [75, 60, 85, 70, 80]}
df = pd.DataFrame(data)

# Transformar el DataFrame para Plotly
df_melted = df.melt(id_vars=['Metric'], var_name='Player', value_name='Score')

# Crear el radar chart
fig = px.line_polar(df_melted, r='Score', theta='Metric', color='Player', line_close=True, 
                    title="Radar Chart: Player Comparison")
fig.show()